/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import javax.swing.JLabel;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;

/**
 *
 * @author Влад
 */
public class NewJFrame extends javax.swing.JFrame {

    char turn;
    boolean game_new;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        this.game_new = false;
        this.turn = 'X';
        initComponents();
    }

    private void tictack(JLabel p) {
        if (p.getText() != null) {
            return;
        }
        if (game_new == true) {
            p.setText(turn + "");
            if (turn == 'X') {
                turn = 'O';
            } else {
                turn = 'X';
            }
            checkgame();
        }
    }

    private void winner(String k) {
        game_new = false;
        button.setText(k + " Won!");
        Label.setText("Click below to start a new game!");
    }

    private void checkgame() {

        button.setText(turn + " Turn");
        String x1 = l1.getText();
        String x2 = l2.getText();
        String x3 = l3.getText();
        String y1 = l4.getText();
        String y2 = l5.getText();
        String y3 = l6.getText();
        String z1 = l7.getText();
        String z2 = l8.getText();
        String z3 = l9.getText();

        if (x1 != null && y1 != null && z1 != null) {
            if ((x1.equals(y1)) && (x1.equals(z1))) {
                winner(x1);
            }
        }

        if (x2 != null && y2 != null && z2 != null) {
            if ((x2.equals(y2)) && (x2.equals(z2))) {
                winner(x2);
            }
        }

        if (x3 != null && y3 != null && z3 != null) {
            if ((x3.equals(y3)) && (x3.equals(z3))) {
                winner(x3);
            }
        }

        if (x1 != null && x2 != null && x3 != null) {
            if ((x1.equals(x2)) && (x1.equals(x3))) {
                winner(x1);
            }
        }

        if (y1 != null && y2 != null && y3 != null) {
            if ((y1.equals(y2)) && (y1.equals(y3))) {
                winner(y1);
            }
        }
        if (z1 != null && z2 != null && z3 != null) {
            if ((z1.equals(z2)) && (z1.equals(z3))) {
                winner(z1);
            }
        }
        if (x1 != null && y2 != null && z3 != null) {
            if ((x1.equals(y2)) && (x1.equals(z3))) {
                winner(x1);
            }
        }
        if (x3 != null && y2 != null && z1 != null) {
            if ((x3.equals(y2)) && (x3.equals(z1))) {
                winner(x3);
            }
        }
        if (game_new == true) {
            if (x1 != null && x2 != null && x3 != null && y1 != null && y2 != null && y3 != null && z1 != null && z2 != null && z3 != null) {
                button.setText("Draw!");
                game_new = false;
                Label.setText("Click below to start a new game!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        button = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("X");
        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l1.setFocusable(false);
        l1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        l1.setMinimumSize(new java.awt.Dimension(39, 60));
        l1.setPreferredSize(new java.awt.Dimension(39, 60));
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 63, 59));

        l2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("O");
        l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l2.setFocusable(false);
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 63, 59));

        l3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("X");
        l3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l3.setFocusable(false);
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 63, 59));

        l4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("O");
        l4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l4.setFocusable(false);
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 63, 59));

        l5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("X");
        l5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        l5.setFocusable(false);
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 63, 59));

        l6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("O");
        l6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l6.setFocusable(false);
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 63, 59));

        l7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 255, 255));
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("X");
        l7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l7.setFocusable(false);
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 63, 59));

        l8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 255, 255));
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("O");
        l8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l8.setFocusable(false);
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
        });
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 63, 59));

        l9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));
        l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l9.setText("X");
        l9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l9.setFocusable(false);
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l9MouseClicked(evt);
            }
        });
        getContentPane().add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 63, 59));

        button.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        button.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        button.setForeground(java.awt.Color.yellow);
        button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button.setText("NEW GAME");
        button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 247, 59));

        Label.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Label.setForeground(new java.awt.Color(255, 255, 255));
        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 247, 20));

        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/wooden.jpg"))); // NOI18N
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background.setName(""); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 267, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        // TODO add your handling code here:
        tictack(l1);
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        // TODO add your handling code here:
        tictack(l2);
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here:
        tictack(l3);
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
        // TODO add your handling code here:
        tictack(l4);
    }//GEN-LAST:event_l4MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
        // TODO add your handling code here:
        tictack(l5);
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
        // TODO add your handling code here:
        tictack(l6);
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
        // TODO add your handling code here:
        tictack(l7);
    }//GEN-LAST:event_l7MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
        // TODO add your handling code here:
        tictack(l8);
    }//GEN-LAST:event_l8MouseClicked

    private void l9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseClicked
        // TODO add your handling code here:
        tictack(l9);
    }//GEN-LAST:event_l9MouseClicked

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
        // TODO add your handling code here:
        if (game_new == false) {
            game_new = true;
            turn = 'X';
            Label.setText("");
            l1.setText(null);
            l2.setText(null);
            l3.setText(null);
            l4.setText(null);
            l5.setText(null);
            l6.setText(null);
            l7.setText(null);
            l8.setText(null);
            l9.setText(null);
            button.setText(turn + " Turn");
        }
    }//GEN-LAST:event_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NewJFrame a = new NewJFrame();
                a.setVisible(true);
                try {
                    Clip clip = AudioSystem.getClip();
                    clip.start();
                    clip.loop(Clip.LOOP_CONTINUOUSLY);
                } catch (LineUnavailableException e) {
                    System.out.println(e.toString());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JLabel background;
    private javax.swing.JLabel button;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
